### PR TITLE
Use an MVar in copyStreamToIteratee to avoid interleaved writes

### PR DESCRIPTION
**Pull request by elliottt**
The ping thread that is forked when the connection is accepted can cause
interleaved writes.  This is likely to occur when the server is sending a large
amount of data down, as the ping thread fires every 30 seconds.  The symptom of
the interleaved writes is the browser closing the connection with a
``Could not decode a text frame as UTF-8'' message.

### CODE REVIEW

**Comment by jaspervdj** [comment]
Which version of `websockets` was this tested with? Since `0.9.2.0`, the `websockets` library itself provides this, meaning it should not call the returned function (`go ref`) in an interleaved way.

**Comment by elliottt** [comment]
I was observing this with version 0.9.2.2 of the websockets library.

**Comment by jaspervdj** [comment]
In that case, I'll both merge this in as a hotfix and dig into the issue in `websockets` more.

**Comment by jaspervdj** [comment]
Thanks for the patch! Should be on Hackage as `websockets-snap-0.9.1.0`.

**Comment by elliottt** [comment]
Thanks for merging so quickly!

**Comment by elliottt** [comment]
I think I spoke too soon.  I'm still seeing the sporadic encoding errors in my development environment, so feel free to roll back this change :(

**Comment by elliottt** [comment]
I'll note that it did decrease the frequency of the encoding error, which is really strange.

**Pull request merged**
